apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-06T14:45:34Z"
  labels:
    run: samplepod
  name: samplepod
  namespace: default
  resourceVersion: "62572"
  uid: d7e84a2b-e2b6-489b-a06a-0e25a9ebf21c
spec:
  containers:
  - image: wordpress
    imagePullPolicy: Always
    name: samplepod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vpvd8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vpvd8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-06T14:45:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-06T14:45:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-06T14:45:51Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-06T14:45:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://46753d87a478da491aa6862e8e7f4150dabfd48f0ba318b78bac97832ec558ca
    image: wordpress:latest
    imageID: docker-pullable://wordpress@sha256:3e28e1e0b732e1828028d7d500eb73f273fc8365215f633414e60cdc631e0d91
    lastState: {}
    name: samplepod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-06T14:45:51Z"
  hostIP: 10.154.0.8
  phase: Running
  podIP: 10.244.2.22
  podIPs:
  - ip: 10.244.2.22
  qosClass: BestEffort
  startTime: "2022-02-06T14:45:34Z"
